#!/bin/bash
echo "Installing Mac automount"

# Change working directory to place where this script is saved
cd "$(dirname "$0")"

source externals/bashutils/validation
source externals/bashutils/colors
source externals/bashutils/error
source externals/bashutils/launchd

source functions.sh

mnt::load_main_config
mnt::validate_all_configs
mnt::save_passwords
mld::create_job "${APP_NAME}" "automount"

echo -e "${GREEN}Finished installing Mac automount${NC}"