#!/bin/bash

# Change working directory to place where this script is saved
cd "$(dirname "$0")"

source externals/bashutils/array
source externals/bashutils/validation
source externals/bashutils/colors
source externals/bashutils/error

source functions.sh

mnt::load_main_config
mnt::validate_all_configs
mnt::process